name: CI Pipeline with Versioning and Docker Deployment

on:
  push:
    branches:
      - main
      - dev
      - feature/*
  pull_request:
    branches:
      - main
      - dev
      - feature/*

jobs:
  calculate-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GITHUB }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Calculate version
      id: version
      run: |
        VERSION_FILE=VERSION
        if [ ! -f "$VERSION_FILE" ]; then echo "0.0.0" > $VERSION_FILE; fi
        CURRENT_VERSION=$(cat $VERSION_FILE)
        echo "Current version: $CURRENT_VERSION"
        
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "Branch name: $BRANCH_NAME"

        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)

        if [[ "$BRANCH_NAME" == "main" ]]; then
          MAJOR=$((MAJOR + 1))
          MINOR=0
          PATCH=0
        elif [[ "$BRANCH_NAME" == "dev" ]]; then
          MINOR=$((MINOR + 1))
          PATCH=0
        elif [[ "$BRANCH_NAME" == feature/* ]]; then
          PATCH=$((PATCH + 1))
        fi

        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "New version: $NEW_VERSION"
        echo $NEW_VERSION > $VERSION_FILE
        echo "::set-output name=version::$NEW_VERSION"

    outputs:
      version: ${{ steps.version.outputs.version }}

  build-docker:
    runs-on: ubuntu-latest
    needs: calculate-version

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GITHUB }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      env:
        VERSION: ${{ needs.calculate-version.outputs.version }}
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
      run: |
        echo "Building Docker image with tag: $DOCKER_REPOSITORY:$VERSION"
        docker build -t $DOCKER_REPOSITORY:$VERSION .

  push-docker:
    runs-on: ubuntu-latest
    needs: [build-docker, calculate-version]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GITHUB }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      env:
        VERSION: ${{ needs.calculate-version.outputs.version }}
        DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY }}
      run: |
        echo "Pushing Docker image to repository: $DOCKER_REPOSITORY:$VERSION"
        docker images
        docker push $DOCKER_REPOSITORY:$VERSION

  tag-repo:
    runs-on: ubuntu-latest
    needs: calculate-version

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GITHUB }}

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Tag version
      env:
        VERSION: ${{ needs.calculate-version.outputs.version }}
      run: |
        echo "Tagging version: $VERSION"
        git tag -a v$VERSION -m "Release version $VERSION"
        git push https://$PAT_GITHUB@github.com/npua-proj/Source.git --tags
